module.exports={
	entry:"./index.js",
	output:{
		path:__dirname+"../../../dist/js",
		filename:"bundle.js"
	},module:{
		loaders:[
			{
				test:/\.css$/,loader:"style-loader!css-loader"
			},
			{
				test:/\.(png|jpe?g|gif|svg)(\?.*)?$/,
				loader:'url-loader',
				options:{
					limit:2048,
					name:'../img/[name].[ext]',
					publicPath:"../../../dist/images/"
				}
			}
		]
	}
};